version: '3'
services:
  auth-ct.vige.it:
    image: "quay.io/keycloak/keycloak:12.0.4"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/workspace/cities-realm.json
    volumes:
      - ./migration:/workspace
  cities-generator-service.vige.it:
    image: "vige/cities-generator"
    ports:
      - "8380:8080"
    environment:
      - COUNTRY=${COUNTRY}