version: '3'
services:
  auth:
    image: "quay.io/keycloak/keycloak:12.0.1"
    ports:
      - "8443:8443"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  citiesgenerator:
    image: "vige/cities-generator"
    ports:
      - "8743:8443"
    environment:
      - COUNTRY=${COUNTRY}