# Vige, Home of Professional Open Source Copyright 2010, Vige, and
# individual contributors by the @authors tag. See the copyright.txt in the
# distribution for a full listing of individual contributors.
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM quay.io/keycloak/keycloak:latest

EXPOSE 8443

ENV REPLACER_CLIENT_ADDRESS=cities-generator-service.vige.it:8743
ENV HOST_NAME=auth-ct.vige.it
VOLUME /opt/keycloak/data
COPY /docker/prod/volume/cert/application-auth.keystore /opt/keycloak/data/cert/application.keystore
COPY /docker/prod/volume/import /opt/keycloak/data/import

USER root
RUN chmod -R 777 /opt/keycloak/data/import
COPY --chmod=755 docker/prod/docker-entrypoint-auth.sh /usr/local/bin/docker-entrypoint-auth.sh
USER 1000

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-auth.sh"]
CMD start --hostname=${HOST_NAME} --https-key-store-file=/opt/keycloak/data/cert/application.keystore --https-key-store-password=${PASSWORD_STORE} --import-realm