version: '3'
services:
  auth-ct.vige.it:
    image: "quay.io/keycloak/keycloak:20.0.1"
    ports:
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start --hostname=auth-ct.vige.it --https-key-store-file=/Users/lucastancapiano/git/cities-generator/service/docker/prod/application.keystore --import-realm
    volumes:
      - ./volume/import:/opt/keycloak/data/import
  cities-generator-service.vige.it:
    image: "vige/cities-generator"
    ports:
      - "8743:8443"
    environment:
      - COUNTRY=${COUNTRY}
    volumes:
      - cities-generator-volume:/root/cities-generator
volumes:
  cities-generator-volume: