version: '3'
services:
  auth-ct.vige.it:
    image: "vige/cities-generator-auth"
    ports:
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - REPLACER_CLIENT_ADDRESS=${REPLACER_CLIENT_ADDRESS}
      - HOST_NAME=${HOST_NAME}
  cities-generator-service.vige.it:
    image: "vige/cities-generator"
    ports:
      - "8743:8443"
    environment:
      - COUNTRY=${COUNTRY}
      - AUTH_URL=${AUTH_URL}